LAEQ/Controllers/MachineController.cs
using LAEQ.DataContexts;
using LAEQ.EntityModel;
using LAEQ.Services;
using LAEQ.ViewModel;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace LAEQ.Controllers
{
    [Authorize(Roles = Roles.CustomRole.Admin)]
    public class MachineController : Controller
    {
        private LAEQEntities db = new LAEQEntities();
        private MachineService service = new MachineService();

        // GET: Machine
        public ActionResult Index()
        {
            var machine = service.GetListMachine();
            return View(new ViewMachine
            {
                ListMachine = machine
            }
            );
        }

        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ViewMachine machine)
        {
            var machines = new Machine
            {
                MachineID = machine.MachineID,
                SerialNumber = machine.SerialNumber,
                Brand = machine.Brand,
                Model = machine.Model,
                Year = machine.Year,
                Capacity = machine.Capacity,
                Status = "Available",
                PM = machine.PM,
                Calibration = machine.Calibration,
                CalibrationDate = machine.CalibrationDate,
                PMDate = machine.PMDate,
                Remark = machine.Remark,
                CreatedDate = DateTime.Now,
                CreatedBy = User.Identity.Name

            };
            if (ModelState.IsValid)
            {
                db.Machines.Add(machines);
                db.SaveChanges();
                return RedirectToAction("Details/" + machines.Id);
            }
            return View(machine);
        }


        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var machine = service.GetMachine(id);
            if (machine == null)
            {
                return HttpNotFound();
            }
            return View(machine);
        }

        public ActionResult Edit(int? id)
        {
            if(id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var machine = service.GetMachine(id);
            if(machine == null)
            {
                return HttpNotFound();
            }
            return View(machine);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ViewMachine machine)
        {
            var machines = new Machine
            {
                Id = machine.Id,
                MachineID = machine.MachineID,
                SerialNumber = machine.SerialNumber,
                Brand = machine.Brand,
                Model = machine.Model,
                Year = machine.Year,
                Capacity = machine.Capacity,
                Status = machine.Status,
                PM = machine.PM,
                Calibration = machine.Calibration,
                CalibrationDate = machine.CalibrationDate,
                PMDate = machine.PMDate,
                Remark = machine.Remark,
                UpdatedBy = User.Identity.Name,
                UpdatedDate = DateTime.Now
            };
            if (ModelState.IsValid)
            {
                db.Entry(machines).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details/" + machines.Id);
            }
            return View(machines);

        }
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var machine = service.GetMachine(id);
            if (machine == null)
            {
                return HttpNotFound();
            }
            return View(machine);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            Machine machine = db.Machines.Find(id);
            machine.DeletedBy = User.Identity.Name;
            machine.DeletedDate = DateTime.Now;
            db.Entry(machine).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

LAEQ/Views/Machine/Create.cshtml
@using LAEQ.ViewModel
@model ViewMachine
@{
    ViewBag.Title = "Create";
}
<script>
    $(document).ready(function()
    {
        $("#CalibrationDate").datepicker();
        $("#PMDate").datepicker();

        var navListItems = $('ul.setup-panel li a'),
           allWells = $('.setup-content');

        allWells.hide();

        navListItems.click(function (e) {
            e.preventDefault();
            var $target = $($(this).attr('href')),
                $item = $(this).closest('li');

            if (!$item.hasClass('disabled')) {
                navListItems.closest('li').removeClass('active');
                $item.addClass('active');
                allWells.hide();
                $target.show();
            }
        });

        $('ul.setup-panel li.active a').trigger('click');


        $('#activate-step-2').on('click', function (e) {
            $('ul.setup-panel li:eq(1)').removeClass('disabled');
            $('ul.setup-panel li a[href="#step-2"]').trigger('click');
            $(this).remove();
        })
    })
</script>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()


    <br />
    <div class="form-horizontal">
        <div class="panel-group">
            <div class="panel panel-default">
                <h4 class="marginleft">Create Machine</h4>
                <hr style="margin-bottom:0;" />
                <div class="panel-body">

                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="row form-group">
                        <div class="col-xs-12">
                            <ul class="nav nav-pills nav-justified thumbnail setup-panel">
                                <li class="active">
                                    <a href="#step-1" class="stepwizard-step">
                                        <h4 class="list-group-item-heading">Machine</h4>
                                        <p class="list-group-item-text"></p>
                                    </a>

                                </li>
                                <li class="disabled">
                                    <a href="#step-2" class="stepwizard-step">
                                        <h4 class="list-group-item-heading"> Detail</h4>
                                        <p class="list-group-item-text"></p>
                                    </a>
                                </li>


                            </ul>
                        </div>
                    </div>

                    <div class="panel-body row setup-content" id="step-1" style="margin-left:10px;">
                        <div class="col-xs-6">
                            <div class="form-group">
                                @Html.LabelFor(model => model.MachineID, "Machine ID", htmlAttributes: new { @class = "control-label col-md-3" })
                                <div class="col-md-9">
                                    @Html.EditorFor(model => model.MachineID, new { htmlAttributes = new { @class = "form-control", @placeholder = " Machine ID" } })
                                    @Html.ValidationMessageFor(model => model.MachineID, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.SerialNumber, "Serial Number", htmlAttributes: new { @class = "control-label col-md-3" })
                                <div class="col-md-9">
                                    @Html.EditorFor(model => model.SerialNumber, new { htmlAttributes = new { @class = "form-control", @placeholder = "Serial Number Machine" } })
                                    @Html.ValidationMessageFor(model => model.SerialNumber, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Brand, htmlAttributes: new { @class = "control-label col-md-3" })
                                <div class="col-md-9">
                                    @Html.EditorFor(model => model.Brand, new { htmlAttributes = new { @class = "form-control", @placeholder = "Brand Machine" } })
                                    @Html.ValidationMessageFor(model => model.Brand, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Model, htmlAttributes: new { @class = "control-label col-md-3" })
                                <div class="col-md-9">
                                    @Html.EditorFor(model => model.Model, new { htmlAttributes = new { @class = "form-control", @placeholder = "Brand Machine" } })
                                    @Html.ValidationMessageFor(model => model.Model, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Year, htmlAttributes: new { @class = "control-label col-md-3" })
                                <div class="col-md-9">
                                    @Html.EditorFor(model => model.Year, new { htmlAttributes = new { @class = "form-control", @placeholder = "Year Machine" } })
                                    @Html.ValidationMessageFor(model => model.Year, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-offset-3 col-md-9">
                                    <input type="button" value="Back Search" class="btn background-docker" onclick="window.location.href='@Url.Action("Index","Machine")'" />
                                    <input type="button" id="activate-step-2" value="Next" class="btn background-docker" />
                                  
                                </div>
                            </div>
                        </div>
                     </div>

                    <div class="panel-body row setup-content" id="step-2" style="margin-left:10px;">

                        <div class="col-xs-6">
                            <div class="form-group">
                                @Html.LabelFor(model => model.Capacity, htmlAttributes: new { @class = "control-label col-md-3" })
                                <div class="col-md-9">
                                    @Html.EditorFor(model => model.Capacity, new { htmlAttributes = new { @class = "form-control", @placeholder = "Capacity Machine" } })
                                    @Html.ValidationMessageFor(model => model.Capacity, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Calibration, htmlAttributes: new { @class = "control-label col-md-3" })
                                <div class="col-md-9">
                                    @Html.DropDownListFor(model => model.Calibration,
                                new List<SelectListItem> {
                                new SelectListItem { Value = "" , Text = "Select Calibaration Type" },
                                new SelectListItem { Value = "None" , Text = "None" },
                                new SelectListItem { Value = "Internal" , Text = "Internal" },
                                 new SelectListItem { Value = "External" , Text = "External" },
                                },
                                new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.Calibration, "", new { @class = "text-danger" })
                                </div>
                            </div>


                            <div class="form-group">
                                @Html.LabelFor(model => model.CalibrationDate, "Calibration Date", htmlAttributes: new { @class = "control-label col-md-3" })
                                <div class="col-md-9">
                                    @Html.EditorFor(model => model.CalibrationDate, new { htmlAttributes = new { @class = "form-control", @placeholder = "Calibration Date Machine" } })
                                    @Html.ValidationMessageFor(model => model.CalibrationDate, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.PM, htmlAttributes: new { @class = "control-label col-md-3" })
                                <div class="col-md-9">
                                    @Html.DropDownListFor(model => model.PM,
                                new List<SelectListItem> {
                                new SelectListItem { Value = "" , Text = "Select PM" },
                                new SelectListItem { Value = "Yes" , Text = "Yes" },
                                new SelectListItem { Value = "No" , Text = "No" },
                                },
                                new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.Calibration, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.PMDate, "PMDate", htmlAttributes: new { @class = "control-label col-md-3" })
                                <div class="col-md-9">
                                    @Html.EditorFor(model => model.PMDate, new { htmlAttributes = new {  @class = "form-control", @placeholder = "PM Date" } })
                                    @Html.ValidationMessageFor(model => model.PMDate, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Remark, htmlAttributes: new { @class = "control-label col-md-3" })
                                <div class="col-md-9">
                                    @Html.TextAreaFor(model => model.Remark,  new { @class = "form-control"  ,@placeholder="Remark" })
                                    @Html.ValidationMessageFor(model => model.Remark, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-offset-3 col-md-10">
                                    <input type="submit" value="Create" class="btn background-docker" />
                                    <input type="button" value="Back Search" class="btn background-docker" onclick="window.location.href='@Url.Action("Index","Machine")'" />
                                </div>
                            </div>
                        </div>
                    </div>

                </div>

            </div>
        </div>
  

        </div>
}

LAEQ/Views/Machine/Delete.cshtml
@using LAEQ.ViewModel
@model ViewMachine

@{
    ViewBag.Title = "Delete";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <br />
    <div class="form-horizontal">
        <div class="panel-group">
            <div class="panel panel-default">
                <h4 class="marginleft">Delete Machine</h4>
                <hr />
                <div class="panel-body">

                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    <div class="form-group">
                        <h4 class="control-label col-md-5">Are you sure you want to delete this?</h4>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.MachineID, "Machine ID ", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-sm-10">
                            <p class="form-control-static">@Model.MachineID</p>
                        </div>
                        @Html.HiddenFor(model => model.Id)
                    </div>
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Delete" class="btn background-docker" />
                            <input type="button" value="Cancel" class="btn background-docker" onclick="window.location.href='@Url.Action("Details","Machine" , new { id = Model.Id })'" />
                        </div>
                    </div>
                </div>

            </div>

        </div>
    </div>

}

LAEQ/Views/Machine/Details.cshtml
@{
    ViewBag.Title = "Details";
}

@using LAEQ.ViewModel
@model ViewMachine

<script>
    $(document).ready(function()
    {
        $("#CalibrationDate").datepicker();
        $("#PMDate").datepicker();

        var navListItems = $('ul.setup-panel li a'),
           allWells = $('.setup-content');

        allWells.hide();

        navListItems.click(function (e) {
            e.preventDefault();
            var $target = $($(this).attr('href')),
                $item = $(this).closest('li');

            if (!$item.hasClass('disabled')) {
                navListItems.closest('li').removeClass('active');
                $item.addClass('active');
                allWells.hide();
                $target.show();
            }
        });

        $('ul.setup-panel li.active a').trigger('click');


        $('#activate-step-2').on('click', function (e) {
            $('ul.setup-panel li:eq(1)').removeClass('disabled');
            $('ul.setup-panel li a[href="#step-2"]').trigger('click');
            $(this).remove();
        })
    })
</script>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()


    <br />
    <div class="form-horizontal">
        <div class="panel-group">
            <div class="panel panel-default">
                <h4 class="marginleft">Details Machine : 
                @if (User.IsInRole("Admin"))
                {
                    <input type="button" value="Edit " class="btn background-docker" onclick="window.location.href='@Url.Action("Edit", "Machine", new { id = Model.Id })'" />
                    <input type="button" value="Delete " class="btn background-docker" onclick="window.location.href='@Url.Action("Delete", "Machine", new { id = Model.Id })'" />
                }
                    <input type="button" value="Back to List " class="btn background-docker" onclick="window.location.href='@Url.Action("Index", "Machine")'" />
                
                </h4>
                <hr style="margin-bottom:0;" />
                <div class="panel-body">

                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="row form-group">
                        <div class="col-xs-12">
                            <ul class="nav nav-pills nav-justified thumbnail setup-panel">
                                <li class="active">
                                    <a href="#step-1" class="stepwizard-step">
                                        <h4 class="list-group-item-heading">Machine</h4>
                                        <p class="list-group-item-text"></p>
                                    </a>

                                </li>
                                <li class="disabled">
                                    <a href="#step-2" class="stepwizard-step">
                                        <h4 class="list-group-item-heading"> Detail</h4>
                                        <p class="list-group-item-text"></p>
                                    </a>
                                </li>


                            </ul>
                        </div>
                    </div>

                    <div class="panel-body row setup-content" id="step-1" style="margin-left:10px;">
                        <div class="col-xs-6">
                            <div class="form-group">
                                @Html.LabelFor(model => model.MachineID, "Machine ID", htmlAttributes: new { @class = "control-label col-md-3" })
                                <div class="col-md-9">
                                    <p class="form-control-static">@Model.MachineID</p>
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.SerialNumber, "Serial Number", htmlAttributes: new { @class = "control-label col-md-3" })
                                <div class="col-md-9">
                                    <p class="form-control-static">@Model.SerialNumber</p>
                                    @Html.ValidationMessageFor(model => model.SerialNumber, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Brand, htmlAttributes: new { @class = "control-label col-md-3" })
                                <div class="col-md-9">
                                    <p class="form-control-static">@Model.Brand</p>
                                    @Html.ValidationMessageFor(model => model.Brand, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Model, htmlAttributes: new { @class = "control-label col-md-3" })
                                <div class="col-md-9">
                                    <p class="form-control-static">@Model.Model</p>
                                    @Html.ValidationMessageFor(model => model.Model, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Year, htmlAttributes: new { @class = "control-label col-md-3" })
                                <div class="col-md-9">
                                    <p class="form-control-static">@Model.Year</p>
                                    @Html.ValidationMessageFor(model => model.Year, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-offset-3 col-md-9">
                                  
                                    <input type="button" id="activate-step-2" value="Next" class="btn background-docker" />

                                </div>
                            </div>
                        </div>
                    </div>
                     <div class="panel-body row setup-content" id="step-2" style="margin-left:10px;">
                            <div class="col-xs-6">
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Capacity, htmlAttributes: new { @class = "control-label col-md-3" })
                                    <div class="col-md-9">
                                        <p class="form-control-static">@Model.Capacity</p>
                                        @Html.ValidationMessageFor(model => model.Capacity, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Calibration, htmlAttributes: new { @class = "control-label col-md-3" })
                                    <div class="col-md-9">
                                        <p class="form-control-static">@Model.Calibration</p>
                                   </div>
                                 </div> 
                                  
                                @if (Model.CalibrationDate != null)
                                {

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.CalibrationDate, "Calibration Date", htmlAttributes: new { @class = "control-label col-md-3" })
                                        <div class="col-md-9">
                                            <p class="form-control-static">@Model.CalibrationDate.Value.ToShortDateString()</p>
                                           
                                        </div>
                                    </div>
                                }
                                else
                                {
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.CalibrationDate, "Calibration Date", htmlAttributes: new { @class = "control-label col-md-3" })
                                        <div class="col-md-9">
                                            <p class="form-control-static">-</p>

                                        </div>
                                    </div>
                                }

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.PM, htmlAttributes: new { @class = "control-label col-md-3" })
                                        <div class="col-md-9">
                                            <p class="form-control-static">@Model.PM</p>
                                        </div>
                                    </div>
                                    @if (Model.PMDate != null)
                                    {
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.PMDate, "PMDate", htmlAttributes: new { @class = "control-label col-md-3" })
                                        <div class="col-md-9">
                                            <p class="form-control-static">@Model.PMDate.Value.ToShortDateString()</p>
                                        </div>
                                    </div>
                                    }
                                    else
                                    {
                                        <div class="form-group">
                                            @Html.LabelFor(model => model.PMDate, "PMDate", htmlAttributes: new { @class = "control-label col-md-3" })
                                            <div class="col-md-9">
                                                <p class="form-control-static">-</p>
                                            </div>
                                        </div>
                                    }

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.Remark, htmlAttributes: new { @class = "control-label col-md-3" })
                                        <div class="col-md-9">
                                            <p class="form-control-static">@Model.Remark</p>
                                        </div>
                                    </div>


                                </div>
                            </div>

                     </div>

                </div>
           


    </div>
    </div>
    
}

LAEQ/Views/Machine/Index.cshtml
@using LAEQ.ViewModel
@model ViewMachine
@{
    ViewBag.Title = "Index";
}




<script>
    var Js;
    $(document).ready(function()
    {
     
        $("#machine").dataTable();

    })
   


</script>

<br />
<div class="form-horizontal">
    <div class="panel-group ">
        <div class="panel panel-default">
            <div class="panel-body">

                <h4 class="marginleft">Machine :
                @if(User.IsInRole("Admin"))
                {
                    <input type="button" value="Create " class="btn background-docker" onclick="window.location.href='@Url.Action("Create","Machine")'" />
                } 
                </h4>
                <br />
                <div class="container">
                    
                    <div class="form-horizontal">
                        <table id="machine" class="table table-bordered">
                            <thead>
                                <tr class="background-docker">
                                    <th>
                                       Machine ID
                                    </th>
                                    <th>
                                       Serial Number
                                    </th>
                                    <th>
                                        Brand
                                    </th>
                                    <th>
                                        Model
                                    </th>
                                    <th>
                                        Capacity
                                    </th>
                                    <th>
                                       Status
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach(var item in Model.ListMachine)
                                {
                                    <tr>
                                        <td>@Html.ActionLink((string)item.MachineID ,"Details", new { id = item.Id })</td>
                                        <td>@item.SerialNumber</td>
                                        <td>@item.Brand</td>
                                        <td>@item.Model</td>
                                        <td>@item.Capacity</td>
                                        <td>@item.Status</td>
                                    </tr>
                                }

                            </tbody>
                        </table>


                    </div>
                </div>

        </div>

    </div>
</div>
</div>